### ISSUE TITLE
import des vvs_mco sur d'autres années + imports visualvalo ssr et visual valo ace ?

### ISSUE THREAD

**Issue by GuillaumePressiat** [IM-HUS/vvs#6]
Bonjour,

Merci pour la publication de ce code. L'approche pour epmsi avec `rstudioapi::askForPassword` est intéressante.

Nous utilisons aussi les sorties de VisualValoSej ainsi que plus récemment les sorties pour le SSR et les ACE.

J'ai des programmes qui utilisent readr et des formats excel pour lire ces tsv correctement et facilement (parsing des dates, des nombres, des . > NA, etc.). Pour le MCO, cela fonctionne de 2010 à 2018.

Je suis partant pour packager ces fonctions et rendre pérenne ce type d'import, voir éventuellement les intégrer en [db](https://im-aphp.github.io/pmeasyr/reference/db_generique.html) directement afin d'éviter leur lecture ultérieure.

La question que je me pose c'est : à l'intérieur de ce package vvs ou bien dans [pmeasyr](https://im-aphp.github.io/pmeasyr/) ?

Votre package vvs propose :
- l'import de vvs 2016
- récupérer des tableaux sur plusieurs périodes (est-ce que le code fonctionne toujours suite à la modification des connexions sur epmsi, via la page sélection de profils ? j'ai une erreur quand je fais tourner la fonction `import_emm_from_epmsi(annee = 2018, mois = 12)` : `Submitting with 'submit'
 Hide Traceback  Error: No links have text 'Applications')`

- reconstruire ces tableaux avec la sortie de vvs, en distinguant l'apport du recodage des évolutions de factures
- d'autres choses encore !

Étant donné les usages différents que nous avons (à la fois sur vvs, mais aussi pour les ace ou le ssr), je me demande comment articuler les fonctions et les packages en temps qu'espaces de travail cohérents, et, réciproquement, de fonctionnalités différentes. Il pourrait être bien de séparer l'import des données de ce qu'on fait de ces données ensuite (chose qui est plus relative aux utilisateurs). 

Qu'en pensez-vous ?

**Comment by jomuller** [comment]
Bonjour Guillaume,

Merci pour ton intérêt sur ce travail.

Sur l'erreur, je n'ai pas eu l'occasion de le tester récemment donc il est probable que le webscrapping ne fonctionne plus s'il y a eu une modification sur epmsi.

Je rejoins ton idée de séparer l'aspect import de l'analyse. En effet, l'import est une tache qui diffère peu d'un établissement à l'autre alors que l'analyse peut être plus spécifique selon les besoins.
Pour info, ce package importe également les données de l'année 2017. Pour l'année 2018, il faut faire des modifications conséquentes car de nouvelles colonnes sont apparues (base remboursable).

J'imagine que par la question de garder un ensemble cohérent tu penses au risque de fragmenter les choses dans différents packages et donc rendre difficile leur utilisation. Dans ce cas, le modèle du tidyverse me paraît le bon. On garde le principe de un package ne fait qu'une chose mais le fait bien et surtout est relativement facile à maintenir. Pour garder la cohérence, on ajoute un metapackage qui appelle tous les autres et on applique des règles entres les différents packages.

J'ai l'impression que c'est ce que vous avez initié à l'AP HP, par exemple avec un seul package qui gère les références (nomensland).

Est-ce que ça répond à la question ?

J'ai peu de temps actuellement pour faire évoluer ces packages mais je reste à l'écoute et je peux donner un coup de main de manière ponctuelle. Donc libre à toi de l'intégrer à pmeasyr puisque tu as la main dessus ou d'imaginer une autre architecture.

**Comment by GuillaumePressiat** [comment]
Bonjour Joris,

Merci de ta réponse, en effet celle-ci répond à ma question.
Je pense que l'on peut partir sur un package séparé des autres pour ce type d'import considérant qu'il y a pas mal de fichiers Visual*quelque_chose désormais : 

[![image](https://user-images.githubusercontent.com/25203135/54640719-c5747300-4a90-11e9-9903-87bda87c14a3.png)](https://atih.sante.fr/plateformes-de-transmission-et-logiciels/logiciels-espace-de-telechargement#V)

Je vais me lancer là-dedans je te tiendrais au courant quand j'aurais avancé. 

Quelques propositions de noms pour ce nouveau package :
- RitualValo (un peu ironique)
- visualvalo (un peu banal)
- VisualpRception (clin d'oeil au côté visuel)
- pmseye (double clin d'oeil, et a l'avantage de donner un peu la couleur PMSI)

D'autres idées ? Histoire de faire cette étape ensemble.

> There are only two hard things in Computer Science: cache invalidation and **naming things**.
> -- Phil Karlton

**Comment by GuillaumePressiat** [comment]
J'ai commencé ici:

https://github.com/GuillaumePressiat/pmsEye

**Comment by jomuller** [comment]
Super ! Je vais suivre ceci.
